#!/bin/bash‏
File="for50guides.csv"
superFolfder="50guides"
pythonScript="/home/labhendel/Documents/Bio_Shir_Reut/guideseq-master/guideseq/guideseq.py"
genom="/home/labhendel/Documents/genome/GCA_000001405.15_GRCh38_no_alt_analysis_set/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna"
outfolder="0.9_15_params_50guides"
min_quality="15"
min_frequency="0.9"
log_file="log50guides_0.9_15"
cat $File |while read line
do
	Folder=$(echo $line | awk '{print $1}');
	target=$(echo $line | awk  -v f=$Folder '$1==f {print $2}');
	echo $name $target

	python $pythonScript umitag --read1 $superFolfder/$Folder.r1.fastq.gz \
	 --read2 $superFolfder/$Folder.r2.fastq.gz \
	 --index1 $superFolfder/$Folder.i1.fastq.gz \
	 --index2 $superFolfder/$Folder.i2.fastq.gz \
	 --outfolder $outfolder/ 2>&1 | tee -a $log_file
	 
	python $pythonScript consolidate --read1 $outfolder/umitagged/$Folder.r1.umitagged.fastq \
	  --read2 $outfolder/umitagged/$Folder.r2.umitagged.fastq \
	  --outfolder $outfolder/ --min_quality $min_quality --min_frequency $min_frequency 2>&1 | tee -a $log_file

	python $pythonScript align --bwa bwa --genome $genom\
	  --read1 $outfolder/consolidated/$Folder.r1.consolidated.fastq\
	  --read2 $outfolder/consolidated/$Folder.r2.consolidated.fastq\
	  --outfolder $outfolder/ 2>&1 | tee -a $log_file
	 
	python $pythonScript identify --aligned $Folder.sam\
	  --genome $genom --outfolder $outfolder/\
	  --target_sequence $target --description $Folder 2>&1 | tee -a $log_file

	python $pythonScript visualize --infile $outfolder/identified/$Folder"_identifiedOfftargets.txt"\
	  --outfolder $outfolder/ --title $Folder 2>&1 | tee -a $log_file
done

